export default {
  CREATE_COURSE: "CREATE_COURSE",
  UPDATE_COURSE: "UPDATE_COURSE",
  LOAD_COURSES: "LOAD_COURSES",
  DELETE_COURSE: "DELETE_COURSE",
  SORT_COURSES: "SORT_COURSES",
  LOAD_AUTHORS: "LOAD_AUTHORS",
};
